# Generated by Django 4.1.5 on 2024-08-17 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('order_item', models.CharField(choices=[('Regular Shawarma', 'Regular Shawarma'), ('Peppered Snail', 'Peppered Snail'), ('Combo Shawarma', 'Combo Shawarma'), ('Spaghetti', 'Spaghetti'), ('Peppered Chicken', 'Peppered Chicken'), ('Small Pan of Asun', 'Big Pan of Asun')], max_length=150)),
                ('order_quantity', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=150)),
                ('special_request', models.TextField()),
            ],
        ),
    ]
